import pandas as pd

df = pd.read_csv("../csv_file/RECIPE_BEFORE_Filter_Have2_drop3.csv", encoding="cp949")
df.dropna(inplace=True)

df.loc[:, "ING_UNIT"].replace(r'\!.*', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('ChiCKg', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[oO]ea', 'ea', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[oO]mL', 'ml', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[oO][rR]ea', 'ea', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[oO][rR]ea', 'ea', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('Zucc', 'ea', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('大', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('Y', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('Can', 'can', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('[gG]', 'g', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('ro', 'ea', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('zo', 'can', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('zjq', 'cup', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'm$', 'M', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[pP]$', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('nL', 'ml', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('cc', 'ml', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('mM', 'mm', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('cM', 'cm', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('M', 'ml', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[mM][lL]', 'ml', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('C', 'cup', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('cup*', 'cup', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[gG]', 'g', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[kK][gG]', 'kg', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'kea.*', 'korea_gram', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('L', 'l', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('T', 't', regex=True, inplace=True)

df.drop(df[df["ING_UNIT"].isin(['', ' ', '  ', '   ', '    '])].index, inplace=True)

df.to_csv("csv_file/ING_BEFORE_Finish.csv", index=False, encoding="cp949")