import pandas as pd

df = pd.read_csv("csv_file/RECIPE_BEFORE_Filter_Have2_drop.csv", encoding="cp949")
df.dropna(inplace=True)


df.loc[:, "ING_UNIT"].replace(r'.*[\%\d\(\)½⅔\~\+].*', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('box', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('bulb', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'a[tT]', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('K정도', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('간보면서하세요', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('×곱배기', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('lb', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('lbs', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('lT', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('liT', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('dl', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('Cl', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('mk', 'ml', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('M', 'm', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('pk', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'P[aA]C[kK]', '', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[\. \'`’]', '', regex=True, inplace=True)


df.loc[:, "ING_UNIT"].replace(r'[kK].*', 'Kg', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('ℓ', 'L', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('lm', 'ml', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('㎖', 'ml', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('lT', 'L', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace('liT', 'L', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[lL].*', 'L', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'c', 'C', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[cC][uU][pP].*', 'C', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'컵.*', 'C', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'공기.*', '공기', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'CC.*', 'cc', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'C[mMn].*', 'cm', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r't', 'T', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'T.*', 'T', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'개.*', 'ea', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'[eE][aA]*', 'ea', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'g', 'G', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'G.*', 'g', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'마리.*', '마리', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'숟갈.*', '숟갈', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'센티.*', 'cm', regex=True, inplace=True)
df.loc[:, "ING_UNIT"].replace(r'장.*', '장', regex=True, inplace=True)
df.drop(df[df["ING_UNIT"].isin([' ', '  ', '   ', '    '])].index, inplace=True)

df.to_csv("csv_file/RECIPE_BEFORE_Filter_Have2_drop2.csv", index=False, encoding="cp949")